"""Initial migration

Revision ID: e60c30be94ff
Revises: 002_add_indexes
Create Date: 2026-05-02 22:55:14.263828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e60c30be94ff'
down_revision: Union[str, None] = '002_add_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analysis_results_contract_id_key'), 'analysis_results', type_='unique')
    op.drop_index(op.f('ix_clauses_risk_level'), table_name='clauses')
    op.add_column('embeddings', sa.Column('context_data', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_embeddings_clause_type'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_type_contract'), table_name='embeddings')
    op.drop_column('embeddings', 'metadata')
    op.drop_index(op.f('ix_reports_expires_at'), table_name='reports')
    op.drop_constraint(op.f('reports_share_uuid_key'), 'reports', type_='unique')
    op.drop_index(op.f('ix_scan_jobs_contract_created'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_constraint(op.f('users_clerk_user_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_clerk_user_id_key'), 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scan_jobs_contract_created'), 'scan_jobs', ['contract_id', 'created_at'], unique=False)
    op.create_unique_constraint(op.f('reports_share_uuid_key'), 'reports', ['share_uuid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_reports_expires_at'), 'reports', ['share_expires_at'], unique=False)
    op.add_column('embeddings', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_embeddings_type_contract'), 'embeddings', ['embedding_type', 'contract_id'], unique=False)
    op.create_index(op.f('ix_embeddings_clause_type'), 'embeddings', ['clause_id', 'embedding_type'], unique=False)
    op.drop_column('embeddings', 'context_data')
    op.create_index(op.f('ix_clauses_risk_level'), 'clauses', ['risk_level'], unique=False)
    op.create_unique_constraint(op.f('analysis_results_contract_id_key'), 'analysis_results', ['contract_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
